[package]
name    = "qwen_image"
version = "0.0.1"
edition = "2026"

[dependencies]
json        = "*"
stdlib      = "*"

[macos.dependencies]
objc          = "*"
metal         = "*"
foundation    = "*"
